### ISSUE TITLE
code

### ISSUE THREAD

**Issue by kivifrt** [lzeeorno/HBFormer-AFFSegNet#1]
你好，我找不到您的一些代码文件，比如preprocess_lits2017_png.py，
这对我很有帮助，请问您可以给予帮助吗？
Hello, I can't find some of your code files like preprocess_lits2017_png.py, this is very helpful to me, can you help me?

**Comment by lzeeorno** [comment]
> 你好，我找不到您的一些代码文件，比如preprocess_lits2017_png.py， 这对我很有帮助，请问您可以给予帮助吗？ Hello, I can't find some of your code files like preprocess_lits2017_png.py, this is very helpful to me, can you help me?

I can't give you the complete code because this article has not been accepted by the conference yet, but I can provide you with the data preprocessing code you requested. The code has been uploaded and you can check it out.

**Comment by lzeeorno** [comment]
code are supported
