### ISSUE TITLE
预训练

### ISSUE THREAD

**Issue by wcx-bit** [lzeeorno/HBFormer-AFFSegNet#2]
请问预训练权重在哪里下载，为什么点了那个here之后跳转的还是这个页面

**Comment by lzeeorno** [comment]
等到文章被接受的时候将会贡献出预训练模型, 不过我相信没有预训练也可以达到文章中提到的效果只是需要训练的时间长久一点. 在LiTS2017数据集中尝试random seed=3407, 在Synapse数据集中尝试random seed=20241017可以帮助更快速的收敛.

**Comment by wcx-bit** [comment]
> 等到文章被接受的时候才会考虑义务贡献出预训练模型, 目前没有义务提供, 不过我相信没有预训练也可以达到文章中提到的效果只是需要训练的时间长久一点. 在LiTS2017数据集中尝试random seed=3407, 在Synapse数据集中尝试random seed=20241017可以帮助更快速的收敛.

感谢你的回复，预祝你的论文被成功接收
